import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';

import "./globals.css";
import Slider from "./Componants/Sliderbar/Slide/Slidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="min-h-screen flex bg-gray-50">
          
          <div className="relative min-h-screen bg-gray-50 overflow-x-hidden">
            <Slider />
          </div>

          <div className="flex-1  overflow-x-hidden container ms:ml-64 ">
            <main className="mt-4">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
